config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'pages/home'
  resources :stories, only: [:new, :create, :show, :index, :update, :destroy]
  get 'pages/profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :subscription
end

app/models/story.rb
require 'rest_client'

class Story < ApplicationRecord
    belongs_to :user
    
    def generate_content
        # Déterminer le nombre de jetons à générer en fonction de l'âge
        case self.age
        when 0..3
          max_tokens = 800  # Testez et ajustez ce nombre pour obtenir environ 300 caractères
        when 4..5
          max_tokens = 1200  # Testez et ajustez ce nombre pour obtenir environ 600 caractères
        else
          max_tokens = 3600  # Testez et ajustez ce nombre pour obtenir environ 800 caractères
        end
      
        input = generate_openai_input
      
        response = RestClient.post(
          "https://api.openai.com/v1/engines/text-davinci-003/completions",
          {
            "prompt" => input,
            "max_tokens" => max_tokens,
            "temperature" => 0.7
          }.to_json,
          {
            "Content-Type" => "application/json",
            "Authorization" => "Bearer #{ENV['OPENAI_API_KEY']}"
          }
        )
      
        story_text = JSON.parse(response.body)['choices'][0]['text']

        # Enlever les espaces blancs au début et à la fin
        story_text = story_text.strip

        # Extraire le titre de l'histoire du texte
        self.title, story_text = story_text.split("\n", 2)
      
        # Générer une conclusion en utilisant la dernière phrase comme invite
        last_sentence = story_text.split(". ").last
        conclusion_prompt = last_sentence + " FIN."
      
        response = RestClient.post(
          "https://api.openai.com/v1/engines/text-davinci-003/completions",
          {
            "prompt" => conclusion_prompt,
            "max_tokens" => 100,  # Vous pouvez ajuster ce nombre selon la longueur souhaitée pour la conclusion
            "temperature" => 0.7
          }.to_json,
          {
            "Content-Type" => "application/json",
            "Authorization" => "Bearer #{ENV['OPENAI_API_KEY']}"
          }
        )
      
        conclusion = JSON.parse(response.body)['choices'][0]['text']
        
        story_text + conclusion
      end
      

      
    def generate_openai_input
        "Raconte moi une histoire pour un enfant de #{age} ans dont le thème est #{theme}, le personnage principal s'appelle #{name}, le personnage secondaire s'appelle #{secondary_character} et son objet fétiche s'appelle #{fav_object}. Commence par le titre de l'histoire."
    end
  end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  has_one :order

  def active?
    expiration_date > Time.now
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
  has_many :subscriptions
  after_create :welcome_send
  has_many :orders

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def subscribed?
    if subscriptions.any?
      exp = subscriptions.all.sample
      subscriptions.each do |sub|
        if sub.expiration_date > exp.expiration_date
          exp = sub
        end
      end
      if exp.expiration_date > Time.now
        return true
      end
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def profile
    @stories = current_user.stories
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :authenticate_user!

    def index
        @stories = Story.all
    end
      
  
    def new
      @story = Story.new
    end
  
    def create
        @story = current_user.stories.new(story_params)
        @story.content = @story.generate_content
        if @story.save
          redirect_to @story
        else
          render 'new'
        end
      end
      
  
    def show
      @story = Story.find(params[:id])
      @openai_input = @story.generate_openai_input
    end

    def update
        @story = Story.find(params[:id])
        if @story.update(story_params)
          redirect_to stories_path, notice: 'Votre histoire a été enregistrée avec succès.'
        else
          render :show
        end
      end

      def destroy
        @story = Story.find(params[:id])
        @story.destroy
    
        redirect_to stories_path, notice: 'L\'histoire a été supprimée avec succès.'
      end  
      
  
    private
  
    def story_params
      params.require(:story).permit(:theme, :age, :name, :secondary_character, :fav_object)
    end

    
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_footer.html.erb
<%# <footer class="footer"> %>
    <p>&copy; 2023 Reverie d'Aedes. All rights reserved.</p>
<%# </footer> %>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReverieAedes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <%= link_to root_path do %>
    <div class="logo"></div>
  <% end %>
  <ul class="country-icons">
      <li><a href="#" id="uk"></a></li>
      <li><a href="#" id="fr"></a></li>
  </ul>
<ul class="navbar-nav">
<% if user_signed_in? %>
    <li><%= link_to "New Story", new_story_path, class: ("active" if current_page?(new_story_path)) %></li> 
    <li><%= link_to "Saved Stories", stories_path, class: ("active" if current_page?(stories_path)) %></li> 
    <li><%= link_to "My stories", "/pages/profile", class: ("active" if current_page?("/pages/profile")) %></li>
    <li><%= link_to "Disconnect", destroy_user_session_path, method: :get %></li>
    
  <% else %>
    <li><%= link_to "Login", new_user_session_path, class: ("active" if current_page?(new_user_session_path)) %></li>
    <li><%= link_to "Subscribe", new_user_registration_path, class: ("active" if current_page?(new_user_registration_path)) %></li>
  <% end %>
</ul>
  <button class="hamburger" id="hamburger"><i class="fa-solid fa-bars" style="color: #ffffff;"></i></button>
  
</nav>

app/views/layouts/application.html.erb
<%= render'layouts/head'%>
<body>
  <div class="container">
    <div class="main-content">
      <header>
        <%= render 'layouts/navbar'%>
      </header>
      <main> 
        <%= yield %>
      </main>
    </div>
    <footer>
      <%= render'layouts/footer'%>
    </footer>  
  </div>

  

  <%= javascript_include_tag 'manifest', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'burgerNav', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'loadingStory', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/b594f069a9.js" crossorigin="anonymous"></script>


</body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<% else %>
  <div class="device-loginSubscribe">
    <%= link_to root_path, style: "text-decoration: none;" do %>
      <div class='signIn-nav-button'>
        Sign In
      </div>
    <% end %>
    <%= link_to root_path, style: "text-decoration: none;" do %>
      <div class='signUp-nav-button'>
        Sign Up
      </div>
    <% end %>
    <%= link_to root_path, style: "text-decoration: none;" do %>
      <div class='about-nav-button'>
        About
      </div>
    <% end %>    
  </div>
<% end %>

app/views/pages/profile.html.erb
<%if current_user.subscriptions.any?%>
    <% exp = current_user.subscriptions.all.sample %>
    <% current_user.subscriptions.each do |sub|%>
        <% if sub.active? %>
            <%if sub.expiration_date >= exp.expiration_date %>
                <%exp = sub%>
            <%end%>
        <%end%>
    <%end%>
<%end%>
<%=current_user.email%><% if current_user.subscribed?%>
 Currently subscribed
<% else %>
Not subscribed
<%end %>
<%if current_user.subscriptions.any?%>
    <%if exp.active?%>
        Time remaining Subscription : 
        <%= distance_of_time_in_words(Time.now,exp.expiration_date,options = {include_seconds: true})%>
    <%else%>
        Your subscription expired <%= distance_of_time_in_words(exp.expiration_date,Time.now,options = {include_seconds: true})%> ago
    <%end%>
<%else%>
    You aren't subscribed
<%end%>


<p> First name = <%=current_user.first_name%>  Last name = <%=current_user.last_name%>
<% button_to 'Edit profile', "/users/edit"%>
<div>
    <%= render @stories %>
</div>

<%if current_user.orders.any? %>
    <table>
        <thead>
            <tr>
                <th>OrderID</th>
                <th>Date of order</th>
                <th>Duration</th>
            </tr>
        </thead>
        <tbody>
            <% (current_user.orders).all.reverse_each do |order| %>
                <tr>
                    <td><%=order.id%> 
                    <td>Ordered the  <%= order.created_at.strftime('%d/%m/%Y') %> at <%= order.created_at.strftime('%H:%M') %> </td>
                    <td>
                        <% sub = order.subscription%>
                        <%= distance_of_time_in_words(sub.start_date,sub.expiration_date,options = {include_seconds: true})%>
                    </td>
                    <td>
                </tr>
            <%end%>
        </tbody>
    </table>
<%end%>

app/views/stories/_story.html.erb
<div class="story-summary">
  <h2>
    <%= link_to story.title, story_path(story), style: "text-decoration: none; color: inherit;" %>
  </h2>
  <p>Créé le <%= story.created_at.to_date %></p>
  <%= link_to 'Supprimer', story_path(story), method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cette histoire?' }, class: "delete-button" %>
</div>

app/views/stories/index.html.erb
<h1 class="title">Saved Stories</h1>

<%= render @stories %>

app/views/stories/new.html.erb
<div id="loading-screen" style="display: none;">
  <p>Histoire en cours de création<span>.</span><span>.</span><span>.</span></p>
</div>

<div class="form-container">
  <%= form_for @story, html: { class: 'form-box' } do |f| %>
    <div class="field">
      <%= f.label :theme %>
      <%= f.select :theme, ["Fairy Tales", "Sci-Fi", "Dongeon and Dragons"], {}, { required: true } %>
    </div>
    
    <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age, required: true, min: 0 %>
  </div>
    
    <div class="field">
      <%= f.label :main_character %>
      <%= f.text_field :name, required: true %>
    </div>

    <div class="field">
      <%= f.label :secondary_character %>
      <%= f.text_field :secondary_character, required: true %>
    </div>

    <div class="field">
      <%= f.label :fav_object %>
      <%= f.text_field :fav_object, required: true %>
    </div>
    
    <div class="actions">
      <%= f.submit "Generate History", class: 'submit-button' %>
    </div>
  <% end %>
</div>

app/views/stories/show.html.erb
<div class="story-card">
  <h2 class="text-center"><%= @story.title %></h2>
  <p><%= @story.content %></p>
</div>